# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Data_edit.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Data_edit(object):
    def setupUi(self, Data_edit):
        Data_edit.setObjectName("Data_edit")
        Data_edit.resize(860, 478)
        Data_edit.setMinimumSize(QtCore.QSize(860, 0))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Data_edit)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(Data_edit)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(860, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.parameter_setting = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.parameter_setting.sizePolicy().hasHeightForWidth())
        self.parameter_setting.setSizePolicy(sizePolicy)
        self.parameter_setting.setMinimumSize(QtCore.QSize(250, 460))
        self.parameter_setting.setMaximumSize(QtCore.QSize(250, 16777215))
        self.parameter_setting.setMouseTracking(True)
        self.parameter_setting.setObjectName("parameter_setting")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.parameter_setting)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Parameter_setting = QtWidgets.QLabel(self.parameter_setting)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Parameter_setting.setFont(font)
        self.Parameter_setting.setObjectName("Parameter_setting")
        self.verticalLayout.addWidget(self.Parameter_setting)
        self.Brain_hot_plot = QtWidgets.QLabel(self.parameter_setting)
        self.Brain_hot_plot.setObjectName("Brain_hot_plot")
        self.verticalLayout.addWidget(self.Brain_hot_plot)
        self.Brain_hot_plot_layout = QtWidgets.QVBoxLayout()
        self.Brain_hot_plot_layout.setObjectName("Brain_hot_plot_layout")
        self.blank_blank = QtWidgets.QHBoxLayout()
        self.blank_blank.setObjectName("blank_blank")
        self.start = QtWidgets.QLineEdit(self.parameter_setting)
        self.start.setMinimumSize(QtCore.QSize(60, 30))
        self.start.setMaximumSize(QtCore.QSize(100000, 30))
        self.start.setObjectName("start")
        self.blank_blank.addWidget(self.start)
        self.line = QtWidgets.QLabel(self.parameter_setting)
        self.line.setMinimumSize(QtCore.QSize(0, 30))
        self.line.setMaximumSize(QtCore.QSize(10000, 30))
        self.line.setObjectName("line")
        self.blank_blank.addWidget(self.line)
        self.end = QtWidgets.QLineEdit(self.parameter_setting)
        self.end.setMinimumSize(QtCore.QSize(60, 30))
        self.end.setMaximumSize(QtCore.QSize(100000, 16777215))
        self.end.setObjectName("end")
        self.blank_blank.addWidget(self.end)
        self.Brain_hot_plot_layout.addLayout(self.blank_blank)
        self.plot_clear = QtWidgets.QHBoxLayout()
        self.plot_clear.setObjectName("plot_clear")
        self.plot = QtWidgets.QPushButton(self.parameter_setting)
        self.plot.setMinimumSize(QtCore.QSize(0, 30))
        self.plot.setObjectName("plot")
        self.plot_clear.addWidget(self.plot)
        self.clear = QtWidgets.QPushButton(self.parameter_setting)
        self.clear.setMinimumSize(QtCore.QSize(0, 30))
        self.clear.setObjectName("clear")
        self.plot_clear.addWidget(self.clear)
        self.Brain_hot_plot_layout.addLayout(self.plot_clear)
        self.verticalLayout.addLayout(self.Brain_hot_plot_layout)
        self.Add_mark_line = QtWidgets.QLabel(self.parameter_setting)
        self.Add_mark_line.setObjectName("Add_mark_line")
        self.verticalLayout.addWidget(self.Add_mark_line)
        self.Mark = QtWidgets.QHBoxLayout()
        self.Mark.setObjectName("Mark")
        self.mark_label = QtWidgets.QLabel(self.parameter_setting)
        self.mark_label.setMinimumSize(QtCore.QSize(60, 30))
        self.mark_label.setMaximumSize(QtCore.QSize(100, 30))
        self.mark_label.setObjectName("mark_label")
        self.Mark.addWidget(self.mark_label)
        self.mark_blank = QtWidgets.QLineEdit(self.parameter_setting)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mark_blank.sizePolicy().hasHeightForWidth())
        self.mark_blank.setSizePolicy(sizePolicy)
        self.mark_blank.setMinimumSize(QtCore.QSize(60, 30))
        self.mark_blank.setMaximumSize(QtCore.QSize(100, 30))
        self.mark_blank.setObjectName("mark_blank")
        self.Mark.addWidget(self.mark_blank)
        self.verticalLayout.addLayout(self.Mark)
        self.Datapoint = QtWidgets.QHBoxLayout()
        self.Datapoint.setObjectName("Datapoint")
        self.datapoint_label = QtWidgets.QLabel(self.parameter_setting)
        self.datapoint_label.setMinimumSize(QtCore.QSize(60, 30))
        self.datapoint_label.setMaximumSize(QtCore.QSize(100, 30))
        self.datapoint_label.setObjectName("datapoint_label")
        self.Datapoint.addWidget(self.datapoint_label)
        self.datapoint_blank = QtWidgets.QLineEdit(self.parameter_setting)
        self.datapoint_blank.setMinimumSize(QtCore.QSize(60, 30))
        self.datapoint_blank.setMaximumSize(QtCore.QSize(100, 30))
        self.datapoint_blank.setObjectName("datapoint_blank")
        self.Datapoint.addWidget(self.datapoint_blank)
        self.verticalLayout.addLayout(self.Datapoint)
        self.Addline_clear_layout = QtWidgets.QHBoxLayout()
        self.Addline_clear_layout.setObjectName("Addline_clear_layout")
        self.Add_line = QtWidgets.QPushButton(self.parameter_setting)
        self.Add_line.setObjectName("Add_line")
        self.Addline_clear_layout.addWidget(self.Add_line)
        self.Clear = QtWidgets.QPushButton(self.parameter_setting)
        self.Clear.setObjectName("Clear")
        self.Addline_clear_layout.addWidget(self.Clear)
        self.Clear_line = QtWidgets.QPushButton(self.parameter_setting)
        self.Clear_line.setMinimumSize(QtCore.QSize(0, 0))
        self.Clear_line.setObjectName("Clear_line")
        self.Addline_clear_layout.addWidget(self.Clear_line)
        self.verticalLayout.addLayout(self.Addline_clear_layout)
        self.Txt_undo_layout = QtWidgets.QHBoxLayout()
        self.Txt_undo_layout.setObjectName("Txt_undo_layout")
        self.From_outside_txt = QtWidgets.QPushButton(self.parameter_setting)
        self.From_outside_txt.setObjectName("From_outside_txt")
        self.Txt_undo_layout.addWidget(self.From_outside_txt)
        self.Undo = QtWidgets.QPushButton(self.parameter_setting)
        self.Undo.setObjectName("Undo")
        self.Txt_undo_layout.addWidget(self.Undo)
        self.verticalLayout.addLayout(self.Txt_undo_layout)
        self.Choose_displayed_channels = QtWidgets.QLabel(self.parameter_setting)
        self.Choose_displayed_channels.setObjectName("Choose_displayed_channels")
        self.verticalLayout.addWidget(self.Choose_displayed_channels)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.channel_choose = QtWidgets.QLineEdit(self.parameter_setting)
        self.channel_choose.setMaximumSize(QtCore.QSize(100, 16777215))
        self.channel_choose.setObjectName("channel_choose")
        self.horizontalLayout_2.addWidget(self.channel_choose)
        self.update_diagram = QtWidgets.QPushButton(self.parameter_setting)
        self.update_diagram.setMaximumSize(QtCore.QSize(150, 16777215))
        self.update_diagram.setObjectName("update_diagram")
        self.horizontalLayout_2.addWidget(self.update_diagram)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.blank = QtWidgets.QLabel(self.parameter_setting)
        self.blank.setMinimumSize(QtCore.QSize(0, 100))
        self.blank.setText("")
        self.blank.setObjectName("blank")
        self.verticalLayout.addWidget(self.blank)
        self.diagram = MatplotlibWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.diagram.sizePolicy().hasHeightForWidth())
        self.diagram.setSizePolicy(sizePolicy)
        self.diagram.setMinimumSize(QtCore.QSize(460, 460))
        self.diagram.setObjectName("diagram")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.diagram)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stack_filter_button = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stack_filter_button.sizePolicy().hasHeightForWidth())
        self.stack_filter_button.setSizePolicy(sizePolicy)
        self.stack_filter_button.setMinimumSize(QtCore.QSize(150, 460))
        self.stack_filter_button.setObjectName("stack_filter_button")
        self.layoutWidget = QtWidgets.QWidget(self.stack_filter_button)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 250, 114, 95))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Stack = QtWidgets.QPushButton(self.layoutWidget)
        self.Stack.setEnabled(True)
        self.Stack.setAcceptDrops(False)
        self.Stack.setCheckable(True)
        self.Stack.setChecked(False)
        self.Stack.setObjectName("Stack")
        self.verticalLayout_2.addWidget(self.Stack)
        self.Filter = QtWidgets.QPushButton(self.layoutWidget)
        self.Filter.setEnabled(True)
        self.Filter.setAcceptDrops(False)
        self.Filter.setCheckable(True)
        self.Filter.setChecked(False)
        self.Filter.setObjectName("Filter")
        self.verticalLayout_2.addWidget(self.Filter)
        self.Reset = QtWidgets.QPushButton(self.layoutWidget)
        self.Reset.setObjectName("Reset")
        self.verticalLayout_2.addWidget(self.Reset)
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(Data_edit)
        QtCore.QMetaObject.connectSlotsByName(Data_edit)

    def retranslateUi(self, Data_edit):
        _translate = QtCore.QCoreApplication.translate
        Data_edit.setWindowTitle(_translate("Data_edit", "Data_edit"))
        self.Parameter_setting.setText(_translate("Data_edit", "Parameter Setting"))
        self.Brain_hot_plot.setText(_translate("Data_edit", "--Brain Hot Plot"))
        self.line.setText(_translate("Data_edit", "----"))
        self.plot.setText(_translate("Data_edit", "plot"))
        self.clear.setText(_translate("Data_edit", "clear"))
        self.Add_mark_line.setText(_translate("Data_edit", "--Add Mark Line"))
        self.mark_label.setText(_translate("Data_edit", "Mark:"))
        self.datapoint_label.setText(_translate("Data_edit", "Datapoint:"))
        self.Add_line.setText(_translate("Data_edit", "Add_line"))
        self.Clear.setText(_translate("Data_edit", "Clear"))
        self.Clear_line.setText(_translate("Data_edit", "Clear_line"))
        self.From_outside_txt.setText(_translate("Data_edit", "From_outside_txt"))
        self.Undo.setText(_translate("Data_edit", "Undo"))
        self.Choose_displayed_channels.setText(_translate("Data_edit", "--Choose displayed channels"))
        self.update_diagram.setText(_translate("Data_edit", "update_diagram"))
        self.Stack.setText(_translate("Data_edit", "Stack"))
        self.Filter.setText(_translate("Data_edit", "Filter(1-64Hz)"))
        self.Reset.setText(_translate("Data_edit", "Reset"))

from MatplotlibWidget import MatplotlibWidget
